routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware(['auth', 'dashboard']);

Route::group(['middleware' => ['auth', 'dashboard']], function () {
    Route::resource('user', 'UserController', ['except' => ['show']])->middleware('admin');
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

    Route::get('company', 'CompanyController@index')->name('company.index');
    Route::get('company/create', 'CompanyController@create')->name('company.create');
    Route::post('company', 'CompanyController@store')->name('company.store');
    Route::get('company/{company}/edit', 'CompanyController@edit')->name('company.edit');
    Route::put('company/{company}', 'CompanyController@update')->name('company.update');
    Route::delete('company/{company}/destroy', 'CompanyController@destroy')->name('company.destroy');

    Route::get('service', 'ServiceController@index')->name('service.index');
    Route::get('service/create', 'ServiceController@create')->name('service.create');
    Route::post('service', 'ServiceController@store')->name('service.store');
    Route::get('service/{service}/edit', 'ServiceController@edit')->name('service.edit');
    Route::put('service/{service}', 'ServiceController@update')->name('service.update');
    Route::delete('service/{service}/destroy', 'ServiceController@destroy')->name('service.destroy');

    Route::post('service/{service}/sub', 'SubServiceController@store')->name('service.sub.store');
    Route::get('service/sub/{sub}/edit', 'SubServiceController@edit')->name('service.sub.edit');
    Route::put('service/sub/{sub}', 'SubServiceController@update')->name('service.sub.update');
    Route::delete('service/sub/{sub}/destroy', 'SubServiceController@destroy')->name('service.sub.destroy');

    Route::get('request', 'RequestsController@index')->name('request.index');
    Route::get('request/create', 'RequestsController@create')->name('request.create');
    Route::post('request', 'RequestsController@store')->name('request.store');
    Route::get('request/{request}/edit', 'RequestsController@edit')->name('request.edit');
    Route::put('request/{request}', 'RequestsController@update')->name('request.update');
    Route::delete('request/{request}/destroy', 'RequestsController@destroy')->name('request.destroy');

    Route::get('offer', 'OffersController@index')->name('offer.index');
    Route::delete('offer/{offer}/destroy', 'OffersController@destroy')->name('offer.destroy');

});


Route::get('request/{request}/map', 'MapController@map')->name('map');
Route::get('googlemap/direction', 'MapController@direction');

resources/views/layouts/navbars/sidebar.blade.php
<div class="sidebar" data-color="orange" data-background-color="white"
     data-image="{{ asset('material') }}/img/sidebar-1.jpg">
    <!--
      Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

      Tip 2: you can also add an image using data-image tag
  -->
    <div class="logo">
        <a href="https://www.digital-edge.sy/" class="simple-text logo-normal">
            {{ __('Digital Edge') }}
        </a>
    </div>
    <div class="sidebar-wrapper">
        <ul class="nav">
            <li class="nav-item{{ $activePage == 'dashboard' ? ' active' : '' }}">
                <a class="nav-link" href="{{ route('home') }}">
                    <i class="material-icons">dashboard</i>
                    <p>{{ __('Dashboard') }}</p>
                </a>
            </li>
            <li class="nav-item {{ ($activePage == 'profile' || $activePage == 'user-management') ? ' active' : '' }}">
                <a class="nav-link" data-toggle="collapse" href="#laravelExample" aria-expanded="true">
                    <i><img style="width:25px" src="https://cdn.onlinewebfonts.com/svg/img_517708.png"></i>
                    <p>{{ __('Roadside Stuff') }}
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse show" id="laravelExample">
                    <ul class="nav">
                        <li class="nav-item{{ $activePage == 'profile' ? ' active' : '' }}">
                            <a class="nav-link" href="{{ route('profile.edit') }}">
                                <span class="sidebar-mini"> MP </span>
                                <span class="sidebar-normal">{{ __('My profile') }} </span>
                            </a>
                        </li>
                        <li class="nav-item{{ $activePage == 'user-management' ? ' active' : '' }}">
                            <a class="nav-link" href="{{ route('user.index') }}">
                                <span class="sidebar-mini"> UM </span>
                                <span class="sidebar-normal"> {{ __('User Management') }} </span>
                            </a>
                        </li>
                        <li class="nav-item{{ $activePage == 'company-management' ? ' active' : '' }}">
                            <a class="nav-link" href="{{ route('company.index') }}">
                                <span class="sidebar-mini"> CM </span>
                                <span class="sidebar-normal"> {{ __('Company Management') }} </span>
                            </a>
                        </li>
                        <li class="nav-item{{ $activePage == 'service-management' ? ' active' : '' }}">
                            <a class="nav-link" href="{{ route('service.index') }}">
                                <span class="sidebar-mini"> SM </span>
                                <span class="sidebar-normal"> {{ __('Service Management') }} </span>
                            </a>
                        </li>
                        <li class="nav-item{{ $activePage == 'request-management' ? ' active' : '' }}">
                            <a class="nav-link" href="{{ route('request.index') }}">
                                <span class="sidebar-mini"> RM </span>
                                <span class="sidebar-normal"> {{ __('Request Management') }} </span>
                            </a>
                        </li>
                        <li class="nav-item{{ $activePage == 'offer-management' ? ' active' : '' }}">
                            <a class="nav-link" href="{{ route('offer.index') }}">
                                <span class="sidebar-mini"> OM </span>
                                <span class="sidebar-normal"> {{ __('Offer Management') }} </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</div>